### ISSUE TITLE
DefaultIcon

### ISSUE THREAD

**Issue by jerodfritz** [jasonkneen/TiCh#12]
Hey Jason,

This is more of a feature request than an issue.  Is it possible to bring over the work you in your TiTh to copy the DefaultIcon.png form theme directory when tich select?

https://github.com/jasonkneen/TiTh/commit/bed751b6d0009c441c6e64ae26ab7814252cb4ea
- Jerod

**Comment by jasonkneen** [comment]
Thanks for the suggestion -- I'm not sure it's the right place for that feature -- TiCh was designed to manipulate the tiapp.xml file only so it feels like TiTh is a better place for this.

**Comment by jerodfritz** [comment]
I understand.  I've added the support in a fork here if someone else comes across the need https://github.com/centogram/TiCh/commit/9c930f4488e6c2f90df7d18f2c1b97ca21d30662

**Comment by jasonkneen** [comment]
ok — do a PR and I’ll merge it — might as well — can you update the readme
too and increment the minor version number in the package.json to 1.0.6?
